### ISSUE TITLE
Instruction 7.

### ISSUE THREAD

**Issue by HidanParra98** [LesFerch/LaunchIE#1]
What command line editor I should use? And how to decompile or edit the file. Be descripting

Thnks

**Comment by LesFerch** [comment]
It's already compiled and ready to run. Just click the download zip link in the readme.

**Comment by LesFerch** [comment]
Or are you asking about how to make a Windows shortcut?

**Comment by LesFerch** [comment]
Step 7 just refers to making a standard Windows shortcut (right-click, create shortcut).
